### PR TITLE
Issue 63 syntax rule access modifiers

### PR DESCRIPTION
**Pull request by atsu85**

### CODE REVIEW

**Comment by atsu85** [comment]
@MeirionHughes, looks like I've used some ES6 features, that are supported on Node v6, but CI uses v5.12.0 - I'll refactor, to make it work with Node 5 as well

**Comment by atsu85** [comment]
I amended my last commit so that now it works on node v5 as well as node v6

**Comment by MeirionHughes** [comment]
I'll merge this as a temporary fix for your use case; but as I mentioned, I'm planning on having a boolean in the config for each reported issue; including differentiating between private and protected.

**Comment by atsu85** [comment]
> I'm planning on having a boolean in the config for each reported issue; including differentiating between private and protected. 

I'd say that private and protected access violations are the same issue - from that perspective it makes more sense to me to have configuration object (as in this PR) for that specific reported issue rather than just boolean (but this PR still supports boolean as well for backwards compatibility)

**Pull request merged**
