### PR TITLE
workaround / fix #92 - workaround for parse5 version differences rela…

### LINKED ISSUE #92: TypeError: Cannot read property 'line' of undefined
**Edit: changed my initial comment after digging deeper**

When i clone and build and link aurelia-template-lint npm module to my project then everything works as expected, but when i do a clean install of gulp-aurelia-template-lint (deleting node_modules before running `npm install`) then i get an error that seems to be related to parsing html/svg elements and its attribute names. 

I suspect that parse5 could be somehow related to this problem:
```
`+-- gulp-aurelia-template-lint@0.9.1
| `-- aurelia-template-lint@0.9.5
|   `-- aurelia-pal-nodejs@1.0.0-alpha.1
|     `-- jsdom@9.4.2
|       `-- parse5@1.5.1
```
but i'm not sure any more, as after manually installing `npm i parse5@2.1.x --save-dev` i have 2 versions (including older parse5@1.5.1), but parse5/package.json visible bellow in stack trace seemed to be the same (@2.1.5)that is installed in aurelia-template-lint as well

```
|   +-- escodegen@1.8.1
|   +-- parse5@1.5.1
+-- parse5@2.1.5
```

but in my project i had 3 versions before running `npm dedupe`.

**So before npm dedupe i got following error (even tough node_modules/parse5 versions in my project and aurelia-template-lint were the same):**
TypeError: Cannot read property 'line' of undefined
    at next.attrs.attrs.map (C:\path\to\aurelia-app\node_modules\aurelia-template-lint\dist\ast.js:26:97)
    at Array.map (native)
    at Parser.parser.on (C:\path\to\aurelia-app\node_modules\aurelia-template-lint\dist\ast.js:22:32)
    at emitMany (events.js:132:20)
    at Parser.emit (events.js:201:7)
    at Parser.SAXParser._handleToken (C:\path\to\aurelia-app\node_modules\template-lint\node_modules\parse5\lib\sax\index.js:171:14)
    at Parser.SAXParser._runParsingLoop (C:\path\to\aurelia-app\node_modules\template-lint\node_modules\parse5\lib\sax\index.js:149:18)
    at Parser.SAXParser._transform (C:\path\to\aurelia-app\node_modules\template-lint\node_modules\parse5\lib\sax\index.js:76:14)
    at Parser.Transform._read (_stream_transform.js:167:10)
    at Parser.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Readable.ondata (_stream_readable.js:556:20)
    at emitOne (events.js:96:13)
    at Readable.emit (events.js:188:7)
    at Readable.read (_stream_readable.js:382:10)
    at flow (_stream_readable.js:762:34)
    at emitReadable_ (_stream_readable.js:434:3)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

### PR DESCRIPTION
**Pull request by atsu85**
…ted to attribute prefix and name

### CODE REVIEW

**Comment by MeirionHughes** [comment]
I was just about to merge... please revert that last dist change and force push.

**Comment by atsu85** [comment]
@MeirionHughes, are You talking about this PR or have You by accident seen my experiment in another branch that I don't plan to use for creating PR?

**Comment by MeirionHughes** [comment]
I can see you're adding content to the dist folder; its becoming part of your PR.

**Comment by atsu85** [comment]
I can't see it as a part of this PR: https://github.com/MeirionHughes/aurelia-template-lint/pull/93/files - no dist folder/files in this PR as i understand

**Comment by atsu85** [comment]
Do You plan to merge this PR, or do You hame some doubts regarding it? As I understand You got confused for a moment, but now You understand it, and this PR is actually OK?

**Comment by MeirionHughes** [comment]
There is versioning mismatch bug between aurelia-template-lint and template-lint. I will fix that first...

**Comment by atsu85** [comment]
Yeah, actually I also discovered/[mentioned](https://github.com/MeirionHughes/aurelia-template-lint/issues/92#issuecomment-240659440) it when writing that comment :D So I also started thinking that maybe the problem is caused by aurelia-template-lint and template-lint versions mismatch.

Anyway ping me when You have resolved the versions mismatch.

**Comment by MeirionHughes** [comment]
Will make a few changes (update typings) then publish.

**Pull request merged**
